filebeat.inputs:
- type: stdin
  enabled: true
  processors:
  - add_fields:
      target: ''
      fields:
        service: transcendence-backend
  - decode_json_fields:
      fields: ["message"]
      target: "json"
      overwrite_keys: true

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

output.logstash:
  hosts: ["logstash:5044"]

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644