version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      # Hot reload : les changements TypeScript sont compilés automatiquement
      - ./frontend/pong:/app/pong:delegated
      - ./frontend/tsconfig.json:/app/tsconfig.json:ro
      - ./frontend/package.json:/app/package.json:ro
      # Exclure node_modules pour éviter les conflits
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    networks:
      - transcendence-network
    stdin_open: true
    tty: true
    stop_grace_period: 2s

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      # Hot reload pour backend
      - ./backend:/app
    networks:
      - transcendence-network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - transcendence-network

networks:
  transcendence-network:
    driver: bridge