version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - transcendence-network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - transcendence-network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - transcendence-network

volumes: {}

networks:
  transcendence-network:
    driver: bridge