server.name: transcendence-kibana
server.host: "0.0.0.0"
server.port: 5601
server.publicBaseUrl: "http://localhost:5601"
elasticsearch.hosts: [ "http://elasticsearch:9200" ]
monitoring.ui.container.elasticsearch.enabled: true
xpack.encryptedSavedObjects.encryptionKey: "transcendence-encryption-key-32-chars-long"
xpack.security.encryptionKey: "transcendence-security-key-32-chars-min"
xpack.reporting.encryptionKey: "transcendence-reporting-key-32-chars"
logging.quiet: true
logging.verbose: false
logging.silent: false
logging.dest: stdout
logging.json: false
# Désactiver les fonctionnalités de sécurité pour l'environnement de dev
xpack.security.enabled: false