{
  "apiVersion": 1,
  "datasources": [
    {
      "name": "Prometheus",
      "type": "prometheus",
      "access": "proxy",
      "url": "http://prometheus:9090",
      "isDefault": true,
      "editable": false,
      "orgId": 1
    },
    {
      "name": "Elasticsearch",
      "type": "elasticsearch",
      "access": "proxy",
      "url": "http://elasticsearch:9200",
      "isDefault": false,
      "editable": false,
      "orgId": 1,
      "database": "transcendence-logs-*",
      "jsonData": {
        "timeField": "@timestamp"
      }
    }
  ]
}
